// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAccountApikeysApiKeyIdData, DeleteAccountApikeysApiKeyIdError, DeleteAccountApikeysApiKeyIdResponse, DeleteAccountData, DeleteAccountError, DeleteAccountResponse, DeleteAdminUsersUserIdData, DeleteAdminUsersUserIdError, DeleteAdminUsersUserIdResponse, GetAccountApikeysData, GetAccountApikeysResponse, GetAccountData, GetAccountError, GetAccountResponse, GetAdminUsersData, GetAdminUsersResponse, GetAdminUsersUserIdData, GetAdminUsersUserIdError, GetAdminUsersUserIdResponse, GetAuthSessionData, GetAuthSessionError, GetAuthSessionResponse, PostAccountApikeysData, PostAccountApikeysError, PostAccountApikeysResponse, PostAdminUsersData, PostAdminUsersError, PostAdminUsersResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthResetPasswordData, PostAuthResetPasswordError, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestError, PostAuthResetPasswordRequestResponse, PostAuthResetPasswordResponse, PutAccountData, PutAccountError, PutAccountPasswordData, PutAccountPasswordError, PutAccountPasswordResponse, PutAccountResponse, PutAdminUsersUserIdData, PutAdminUsersUserIdError, PutAdminUsersUserIdPasswordData, PutAdminUsersUserIdPasswordError, PutAdminUsersUserIdPasswordResponse, PutAdminUsersUserIdResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <TComposable extends Composable = '$fetch', DefaultT extends GetAuthSessionResponse = GetAuthSessionResponse>(options: Options<TComposable, GetAuthSessionData, GetAuthSessionResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAuthSessionResponse | DefaultT, GetAuthSessionError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * User Logout
 *
 * Invalidate the current user's session
 */
export const postAuthLogout = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLogoutResponse = PostAuthLogoutResponse>(options: Options<TComposable, PostAuthLogoutData, PostAuthLogoutResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLogoutResponse | DefaultT, PostAuthLogoutError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Reset your password for reset token
 *
 * Reset your password using a valid reset token
 */
export const postAuthResetPassword = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordResponse = PostAuthResetPasswordResponse>(options: Options<TComposable, PostAuthResetPasswordData, PostAuthResetPasswordResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthResetPasswordResponse | DefaultT, PostAuthResetPasswordError, DefaultT>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request Password Reset
 *
 * Request a password reset for a user using their username
 */
export const postAuthResetPasswordRequest = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponse>(options: Options<TComposable, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthResetPasswordRequestResponse | DefaultT, PostAuthResetPasswordRequestError, DefaultT>({
    url: '/auth/reset-password/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete account
 *
 * Permanently delete the authenticated user's account.
 */
export const deleteAccount = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountResponse = DeleteAccountResponse>(options: Options<TComposable, DeleteAccountData, DeleteAccountResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteAccountResponse | DefaultT, DeleteAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Get account information
 *
 * Retrieve information about the authenticated user's account.
 */
export const getAccount = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountResponse = GetAccountResponse>(options: Options<TComposable, GetAccountData, GetAccountResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAccountResponse | DefaultT, GetAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Update account information
 *
 * Update information about the authenticated user's account.
 */
export const putAccount = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountResponse = PutAccountResponse>(options: Options<TComposable, PutAccountData, PutAccountResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAccountResponse | DefaultT, PutAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change account password
 *
 * Change the password of the authenticated user's account.
 */
export const putAccountPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountPasswordResponse = PutAccountPasswordResponse>(options: Options<TComposable, PutAccountPasswordData, PutAccountPasswordResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAccountPasswordResponse | DefaultT, PutAccountPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all API keys
 *
 * Retrieve all API keys for the authenticated user's account.
 */
export const getAccountApikeys = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountApikeysResponse = GetAccountApikeysResponse>(options: Options<TComposable, GetAccountApikeysData, GetAccountApikeysResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAccountApikeysResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options
});

/**
 * Create a new API key
 *
 * Create a new API key for the authenticated user's account.
 */
export const postAccountApikeys = <TComposable extends Composable = '$fetch', DefaultT extends PostAccountApikeysResponse = PostAccountApikeysResponse>(options: Options<TComposable, PostAccountApikeysData, PostAccountApikeysResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAccountApikeysResponse | DefaultT, PostAccountApikeysError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an API key
 *
 * Delete an API key by its ID for the authenticated user's account.
 */
export const deleteAccountApikeysApiKeyId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountApikeysApiKeyIdResponse = DeleteAccountApikeysApiKeyIdResponse>(options: Options<TComposable, DeleteAccountApikeysApiKeyIdData, DeleteAccountApikeysApiKeyIdResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteAccountApikeysApiKeyIdResponse | DefaultT, DeleteAccountApikeysApiKeyIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys/{apiKeyID}',
    ...options
});

/**
 * List users
 *
 * Retrieve Delivr accounts with optional role and search filters.
 */
export const getAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersResponse = GetAdminUsersResponse>(options: Options<TComposable, GetAdminUsersData, GetAdminUsersResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAdminUsersResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create user
 *
 * Provision a new Delivr account with the desired role.
 */
export const postAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends PostAdminUsersResponse = PostAdminUsersResponse>(options: Options<TComposable, PostAdminUsersData, PostAdminUsersResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAdminUsersResponse | DefaultT, PostAdminUsersError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 *
 * Permanently remove a Delivr account after verifying it has no owned packages.
 */
export const deleteAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAdminUsersUserIdResponse = DeleteAdminUsersUserIdResponse>(options: Options<TComposable, DeleteAdminUsersUserIdData, DeleteAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteAdminUsersUserIdResponse | DefaultT, DeleteAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Get user
 *
 * Retrieve details for a specific Delivr account.
 */
export const getAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersUserIdResponse = GetAdminUsersUserIdResponse>(options: Options<TComposable, GetAdminUsersUserIdData, GetAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAdminUsersUserIdResponse | DefaultT, GetAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Modify profile fields or role for a Delivr account.
 */
export const putAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersUserIdResponse = PutAdminUsersUserIdResponse>(options: Options<TComposable, PutAdminUsersUserIdData, PutAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAdminUsersUserIdResponse | DefaultT, PutAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 *
 * Set a new password for a Delivr account and revoke active sessions.
 */
export const putAdminUsersUserIdPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersUserIdPasswordResponse = PutAdminUsersUserIdPasswordResponse>(options: Options<TComposable, PutAdminUsersUserIdPasswordData, PutAdminUsersUserIdPasswordResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAdminUsersUserIdPasswordResponse | DefaultT, PutAdminUsersUserIdPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
