// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:14123' | 'https://api.delivr.is-on.net' | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body?: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Please delete all mail accounts associated with this account before deleting the account
     */
    400: {
        success: false;
        code: 400;
        message: 'Please delete all mail accounts associated with this account before deleting the account';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        /**
         * Username for the account
         */
        username?: string;
        display_name?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body?: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysByApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysByApiKeyIdError = DeleteAccountApikeysByApiKeyIdErrors[keyof DeleteAccountApikeysByApiKeyIdErrors];

export type DeleteAccountApikeysByApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysByApiKeyIdResponse = DeleteAccountApikeysByApiKeyIdResponses[keyof DeleteAccountApikeysByApiKeyIdResponses];

export type GetAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type GetAccountApikeysByApiKeyIdErrors = {
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type GetAccountApikeysByApiKeyIdError = GetAccountApikeysByApiKeyIdErrors[keyof GetAccountApikeysByApiKeyIdErrors];

export type GetAccountApikeysByApiKeyIdResponses = {
    /**
     * API key retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key retrieved successfully';
        data: {
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        };
    };
};

export type GetAccountApikeysByApiKeyIdResponse = GetAccountApikeysByApiKeyIdResponses[keyof GetAccountApikeysByApiKeyIdResponses];

export type GetMailAccountsData = {
    body?: never;
    path?: never;
    query?: {
        withMailboxes?: boolean;
    };
    url: '/mail-accounts';
};

export type GetMailAccountsResponses = {
    /**
     * Mail accounts retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail accounts retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            display_name: string;
            is_default: boolean;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            smtp_username: string;
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_username: string;
        }> | Array<{
            id: number;
            created_at: number;
            display_name: string;
            is_default: boolean;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            smtp_username: string;
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_username: string;
            mailboxes: Array<{
                name: string;
                path: string;
                delimiter: string;
                parent: Array<string>;
                parentPath: string;
                flags: Array<string>;
                specialUse?: string;
                status: {
                    /**
                     * Total number of messages in the mailbox
                     */
                    messages: number;
                    /**
                     * Number of recent messages in the mailbox
                     */
                    recent: number;
                    /**
                     * Number of unseen (unread) messages in the mailbox
                     */
                    unseen: number;
                };
            }>;
        }>;
    };
};

export type GetMailAccountsResponse = GetMailAccountsResponses[keyof GetMailAccountsResponses];

export type PostMailAccountsData = {
    body?: {
        display_name: string;
        is_default?: boolean;
        smtp_host: string | string | string;
        /**
         * Port
         */
        smtp_port: number;
        smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        smtp_username: string;
        smtp_password: string;
        imap_host: string | string | string;
        /**
         * Port
         */
        imap_port: number;
        imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        imap_username: string;
        imap_password: string;
    };
    path?: never;
    query?: never;
    url: '/mail-accounts';
};

export type PostMailAccountsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsError = PostMailAccountsErrors[keyof PostMailAccountsErrors];

export type PostMailAccountsResponses = {
    /**
     * Mail account created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account created successfully';
        data: {
            id: number;
        };
    };
};

export type PostMailAccountsResponse = PostMailAccountsResponses[keyof PostMailAccountsResponses];

export type DeleteMailAccountsByMailAccountIdData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}';
};

export type DeleteMailAccountsByMailAccountIdErrors = {
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type DeleteMailAccountsByMailAccountIdError = DeleteMailAccountsByMailAccountIdErrors[keyof DeleteMailAccountsByMailAccountIdErrors];

export type DeleteMailAccountsByMailAccountIdResponses = {
    /**
     * Mail account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account deleted successfully';
        data: null;
    };
};

export type DeleteMailAccountsByMailAccountIdResponse = DeleteMailAccountsByMailAccountIdResponses[keyof DeleteMailAccountsByMailAccountIdResponses];

export type GetMailAccountsByMailAccountIdData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: {
        withMailboxes?: boolean;
    };
    url: '/mail-accounts/{mailAccountID}';
};

export type GetMailAccountsByMailAccountIdErrors = {
    /**
     * Mail Account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail Account with the specified ID not found';
    };
};

export type GetMailAccountsByMailAccountIdError = GetMailAccountsByMailAccountIdErrors[keyof GetMailAccountsByMailAccountIdErrors];

export type GetMailAccountsByMailAccountIdResponses = {
    /**
     * Mail account retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account retrieved successfully';
        data: {
            id: number;
            created_at: number;
            display_name: string;
            is_default: boolean;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            smtp_username: string;
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_username: string;
        } | {
            id: number;
            created_at: number;
            display_name: string;
            is_default: boolean;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            smtp_username: string;
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_username: string;
            mailboxes: Array<{
                name: string;
                path: string;
                delimiter: string;
                parent: Array<string>;
                parentPath: string;
                flags: Array<string>;
                specialUse?: string;
                status: {
                    /**
                     * Total number of messages in the mailbox
                     */
                    messages: number;
                    /**
                     * Number of recent messages in the mailbox
                     */
                    recent: number;
                    /**
                     * Number of unseen (unread) messages in the mailbox
                     */
                    unseen: number;
                };
            }>;
        };
    };
};

export type GetMailAccountsByMailAccountIdResponse = GetMailAccountsByMailAccountIdResponses[keyof GetMailAccountsByMailAccountIdResponses];

export type PutMailAccountsByMailAccountIdData = {
    body?: {
        display_name?: string;
        is_default?: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}';
};

export type PutMailAccountsByMailAccountIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type PutMailAccountsByMailAccountIdError = PutMailAccountsByMailAccountIdErrors[keyof PutMailAccountsByMailAccountIdErrors];

export type PutMailAccountsByMailAccountIdResponses = {
    /**
     * Mail account updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account updated successfully';
        data: null;
    };
};

export type PutMailAccountsByMailAccountIdResponse = PutMailAccountsByMailAccountIdResponses[keyof PutMailAccountsByMailAccountIdResponses];

export type PutMailAccountsByMailAccountIdCredentialsData = {
    body?: {
        smtp_host: string | string | string;
        /**
         * Port
         */
        smtp_port: number;
        smtp_username: string;
        smtp_password: string;
        smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        imap_host: string | string | string;
        /**
         * Port
         */
        imap_port: number;
        imap_username: string;
        imap_password: string;
        imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/credentials';
};

export type PutMailAccountsByMailAccountIdCredentialsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type PutMailAccountsByMailAccountIdCredentialsError = PutMailAccountsByMailAccountIdCredentialsErrors[keyof PutMailAccountsByMailAccountIdCredentialsErrors];

export type PutMailAccountsByMailAccountIdCredentialsResponses = {
    /**
     * Mail account credentials updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account credentials updated successfully';
        data: null;
    };
};

export type PutMailAccountsByMailAccountIdCredentialsResponse = PutMailAccountsByMailAccountIdCredentialsResponses[keyof PutMailAccountsByMailAccountIdCredentialsResponses];

export type GetMailAccountsByMailAccountIdMailboxesData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes';
};

export type GetMailAccountsByMailAccountIdMailboxesResponses = {
    /**
     * Mailboxes retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailboxes retrieved successfully';
        data: Array<{
            name: string;
            path: string;
            delimiter: string;
            parent: Array<string>;
            parentPath: string;
            flags: Array<string>;
            specialUse?: string;
            status: {
                /**
                 * Total number of messages in the mailbox
                 */
                messages: number;
                /**
                 * Number of recent messages in the mailbox
                 */
                recent: number;
                /**
                 * Number of unseen (unread) messages in the mailbox
                 */
                unseen: number;
            };
        }>;
    };
};

export type GetMailAccountsByMailAccountIdMailboxesResponse = GetMailAccountsByMailAccountIdMailboxesResponses[keyof GetMailAccountsByMailAccountIdMailboxesResponses];

export type PostMailAccountsByMailAccountIdMailboxesData = {
    body?: {
        path: string;
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes';
};

export type PostMailAccountsByMailAccountIdMailboxesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsByMailAccountIdMailboxesError = PostMailAccountsByMailAccountIdMailboxesErrors[keyof PostMailAccountsByMailAccountIdMailboxesErrors];

export type PostMailAccountsByMailAccountIdMailboxesResponses = {
    /**
     * Mailbox created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailbox created successfully';
        data: null;
    };
};

export type PostMailAccountsByMailAccountIdMailboxesResponse = PostMailAccountsByMailAccountIdMailboxesResponses[keyof PostMailAccountsByMailAccountIdMailboxesResponses];

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}';
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathError = DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathErrors[keyof DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathErrors];

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathResponses = {
    /**
     * Mailbox deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailbox deleted successfully';
        data: null;
    };
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathResponses[keyof DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathResponses];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}';
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathErrors = {
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathError = GetMailAccountsByMailAccountIdMailboxesByMailboxPathErrors[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathErrors];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathResponses = {
    /**
     * Mailbox info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailbox info retrieved successfully';
        data: {
            name: string;
            path: string;
            delimiter: string;
            parent: Array<string>;
            parentPath: string;
            flags: Array<string>;
            specialUse?: string;
            status: {
                /**
                 * Total number of messages in the mailbox
                 */
                messages: number;
                /**
                 * Number of recent messages in the mailbox
                 */
                recent: number;
                /**
                 * Number of unseen (unread) messages in the mailbox
                 */
                unseen: number;
            };
        };
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = GetMailAccountsByMailAccountIdMailboxesByMailboxPathResponses[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathResponses];

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathData = {
    body?: {
        path: string;
    };
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}';
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathError = PutMailAccountsByMailAccountIdMailboxesByMailboxPathErrors[keyof PutMailAccountsByMailAccountIdMailboxesByMailboxPathErrors];

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathResponses = {
    /**
     * Mailbox updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailbox updated successfully';
        data: null;
    };
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = PutMailAccountsByMailAccountIdMailboxesByMailboxPathResponses[keyof PutMailAccountsByMailAccountIdMailboxesByMailboxPathResponses];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/status';
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusErrors = {
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusError = GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusErrors[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusErrors];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusResponses = {
    /**
     * Mailbox status retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mailbox status retrieved successfully';
        data: {
            /**
             * Total number of messages in the mailbox
             */
            messages: number;
            /**
             * Number of recent messages in the mailbox
             */
            recent: number;
            /**
             * Number of unseen (unread) messages in the mailbox
             */
            unseen: number;
        };
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusResponse = GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusResponses[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusResponses];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails';
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors = {
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsError = GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses = {
    /**
     * Mails retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mails retrieved successfully';
        data: Array<{
            uid: number;
            rawHeaders: {
                [key: string]: string;
            };
            rawFlags: Array<string>;
            from?: {
                name?: string;
                address: string;
            };
            to: Array<{
                name?: string;
                address: string;
            }>;
            cc: Array<{
                name?: string;
                address: string;
            }>;
            bcc: Array<{
                name?: string;
                address: string;
            }>;
            subject?: string;
            references?: string | Array<string>;
            date?: number;
            flags?: {
                seen?: boolean;
                answered?: boolean;
                flagged?: boolean;
                deleted?: boolean;
                draft?: boolean;
                recent?: boolean;
            };
            replyTo?: Array<{
                name?: string;
                address: string;
            }>;
            messageId?: string;
            inReplyTo?: string;
            priority?: 'normal' | 'low' | 'high';
            attachments: Array<{
                filename?: string;
                contentType: string;
                size: number;
                contentId?: string;
                contentDisposition?: string;
            }>;
            body: {
                text?: string;
                html?: string;
            };
        }>;
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponse = GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsData = {
    body?: {
        from?: {
            name?: string;
            address: string;
        };
        to: Array<{
            name?: string;
            address: string;
        }>;
        cc: Array<{
            name?: string;
            address: string;
        }>;
        bcc: Array<{
            name?: string;
            address: string;
        }>;
        subject?: string;
        references?: string | Array<string>;
        flags?: {
            seen?: boolean;
            answered?: boolean;
            flagged?: boolean;
            deleted?: boolean;
            draft?: boolean;
            recent?: boolean;
        };
        replyTo?: Array<{
            name?: string;
            address: string;
        }>;
        messageId?: string;
        inReplyTo?: string;
        priority?: 'normal' | 'low' | 'high';
        body: {
            text?: string;
            html?: string;
        };
    };
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails';
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mailbox with specified path not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mailbox with specified path not found';
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsError = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsErrors];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses = {
    /**
     * Mail created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail created successfully';
        data: {
            uid: number;
        };
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponse = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponses];

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
        mailUID: number;
    };
    query?: {
        /**
         * If true, permanently delete the mail. Otherwise, move to Trash.
         */
        permanent?: boolean;
    };
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails/{mailUID}';
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidError = DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors[keyof DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors];

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses = {
    /**
     * Mail deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail deleted successfully';
        data: {
            success: boolean;
        };
    };
};

export type DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses[keyof DeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidData = {
    body?: never;
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
        mailUID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails/{mailUID}';
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidError = GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors];

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses = {
    /**
     * Mail retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail retrieved successfully';
        data: {
            uid: number;
            rawHeaders: {
                [key: string]: string;
            };
            rawFlags: Array<string>;
            from?: {
                name?: string;
                address: string;
            };
            to: Array<{
                name?: string;
                address: string;
            }>;
            cc: Array<{
                name?: string;
                address: string;
            }>;
            bcc: Array<{
                name?: string;
                address: string;
            }>;
            subject?: string;
            references?: string | Array<string>;
            date?: number;
            flags?: {
                seen?: boolean;
                answered?: boolean;
                flagged?: boolean;
                deleted?: boolean;
                draft?: boolean;
                recent?: boolean;
            };
            replyTo?: Array<{
                name?: string;
                address: string;
            }>;
            messageId?: string;
            inReplyTo?: string;
            priority?: 'normal' | 'low' | 'high';
            attachments: Array<{
                filename?: string;
                contentType: string;
                size: number;
                contentId?: string;
                contentDisposition?: string;
            }>;
            body: {
                text?: string;
                html?: string;
            };
        };
    };
};

export type GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses[keyof GetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses];

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidData = {
    body?: {
        from?: {
            name?: string;
            address: string;
        };
        to?: Array<{
            name?: string;
            address: string;
        }>;
        cc?: Array<{
            name?: string;
            address: string;
        }>;
        bcc?: Array<{
            name?: string;
            address: string;
        }>;
        subject?: string;
        references?: string | Array<string>;
        flags?: {
            seen?: boolean;
            answered?: boolean;
            flagged?: boolean;
            deleted?: boolean;
            draft?: boolean;
            recent?: boolean;
        };
        replyTo?: Array<{
            name?: string;
            address: string;
        }>;
        messageId?: string;
        inReplyTo?: string;
        priority?: 'normal' | 'low' | 'high';
        body?: {
            text?: string;
            html?: string;
        };
    };
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
        mailUID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails/{mailUID}';
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidError = PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors[keyof PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidErrors];

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses = {
    /**
     * Mail updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail updated successfully';
        data: {
            success: boolean;
            /**
             * New UID if the mail was replaced (for content updates)
             */
            newUid?: number;
        };
    };
};

export type PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses[keyof PutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponses];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendData = {
    body?: {
        /**
         * Whether to move the original mail to Sent folder after sending
         */
        moveToSent?: boolean;
        /**
         * Whether to delete the original mail after sending (only if moveToSent is false)
         */
        deleteOriginal?: boolean;
    };
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
        mailUID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails/{mailUID}/send';
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendError = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendErrors[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendErrors];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendResponses = {
    /**
     * Mail sent successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail sent successfully';
        data: {
            /**
             * The Message-ID of the sent mail
             */
            messageId?: string;
        };
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendResponse = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendResponses[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendResponses];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveData = {
    body?: {
        /**
         * The path of the target mailbox to move the mail to
         */
        targetMailbox: string;
    };
    path: {
        mailAccountID: number;
        /**
         * URI-encoded mailbox path
         */
        mailboxPath: string;
        mailUID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mailboxes/{mailboxPath}/mails/{mailUID}/move';
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveError = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveErrors[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveErrors];

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveResponses = {
    /**
     * Mail moved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail moved successfully';
        data: {
            /**
             * The new UID of the mail in the target mailbox, if available
             */
            newUid?: number;
        };
    };
};

export type PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveResponse = PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveResponses[keyof PostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveResponses];

export type GetMailAccountsByMailAccountIdIdentitiesData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities';
};

export type GetMailAccountsByMailAccountIdIdentitiesResponses = {
    /**
     * Mail identities retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identities retrieved successfully';
        data: Array<{
            id: number;
            mail_account_id: number;
            created_at: number;
            display_name: string;
            email_address: string;
            is_default: boolean;
        }>;
    };
};

export type GetMailAccountsByMailAccountIdIdentitiesResponse = GetMailAccountsByMailAccountIdIdentitiesResponses[keyof GetMailAccountsByMailAccountIdIdentitiesResponses];

export type PostMailAccountsByMailAccountIdIdentitiesData = {
    body?: {
        display_name: string;
        email_address: string;
        is_default: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities';
};

export type PostMailAccountsByMailAccountIdIdentitiesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsByMailAccountIdIdentitiesError = PostMailAccountsByMailAccountIdIdentitiesErrors[keyof PostMailAccountsByMailAccountIdIdentitiesErrors];

export type PostMailAccountsByMailAccountIdIdentitiesResponses = {
    /**
     * Mail identity created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity created successfully';
        data: {
            id: number;
        };
    };
};

export type PostMailAccountsByMailAccountIdIdentitiesResponse = PostMailAccountsByMailAccountIdIdentitiesResponses[keyof PostMailAccountsByMailAccountIdIdentitiesResponses];

export type DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdData = {
    body?: never;
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdError = DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors[keyof DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors];

export type DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses = {
    /**
     * Mail identity deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity deleted successfully';
        data: null;
    };
};

export type DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses[keyof DeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses];

export type GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdData = {
    body?: never;
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors = {
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdError = GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors[keyof GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors];

export type GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses = {
    /**
     * Mail identity retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity retrieved successfully';
        data: {
            id: number;
            created_at: number;
            display_name: string;
            email_address: string;
            is_default: boolean;
        };
    };
};

export type GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses[keyof GetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses];

export type PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdData = {
    body?: {
        display_name?: string;
        email_address?: string;
        is_default?: boolean;
    };
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdError = PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors[keyof PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdErrors];

export type PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses = {
    /**
     * Mail identity updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity updated successfully';
        data: null;
    };
};

export type PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses[keyof PutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponses];

export type GetMailAccountsByMailAccountIdSearchData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query: {
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort order by email date
         */
        order?: 'newest' | 'oldest';
        /**
         * Maximum number of results to return
         */
        limit?: number;
        /**
         * Number of results to skip for pagination
         */
        offset?: number;
        /**
         * Include Trash/Deleted items folder in search
         */
        includeTrash?: boolean;
        /**
         * Include Spam/Junk folder in search
         */
        includeSpam?: boolean;
    };
    url: '/mail-accounts/{mailAccountID}/search';
};

export type GetMailAccountsByMailAccountIdSearchResponses = {
    /**
     * Search completed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Search completed successfully';
        data: {
            /**
             * Total number of matching emails across all searched mailboxes
             */
            total: number;
            /**
             * Number of mailboxes that were searched
             */
            mailboxesSearched: number;
            /**
             * Array of search results with mailbox information
             */
            results: Array<{
                /**
                 * Path of the mailbox containing this email
                 */
                mailboxPath: string;
                /**
                 * Display name of the mailbox
                 */
                mailboxName: string;
                /**
                 * Special use flag (e.g., \Sent, \Drafts, \Trash)
                 */
                specialUse?: string;
                mail: {
                    uid: number;
                    rawHeaders: {
                        [key: string]: string;
                    };
                    rawFlags: Array<string>;
                    from?: {
                        name?: string;
                        address: string;
                    };
                    to: Array<{
                        name?: string;
                        address: string;
                    }>;
                    cc: Array<{
                        name?: string;
                        address: string;
                    }>;
                    bcc: Array<{
                        name?: string;
                        address: string;
                    }>;
                    subject?: string;
                    references?: string | Array<string>;
                    date?: number;
                    flags?: {
                        seen?: boolean;
                        answered?: boolean;
                        flagged?: boolean;
                        deleted?: boolean;
                        draft?: boolean;
                        recent?: boolean;
                    };
                    replyTo?: Array<{
                        name?: string;
                        address: string;
                    }>;
                    messageId?: string;
                    inReplyTo?: string;
                    priority?: 'normal' | 'low' | 'high';
                    attachments: Array<{
                        filename?: string;
                        contentType: string;
                        size: number;
                        contentId?: string;
                        contentDisposition?: string;
                    }>;
                    body: {
                        text?: string;
                        html?: string;
                    };
                };
            }>;
        };
    };
};

export type GetMailAccountsByMailAccountIdSearchResponse = GetMailAccountsByMailAccountIdSearchResponses[keyof GetMailAccountsByMailAccountIdSearchResponses];

export type PostMailAccountsByMailAccountIdSearchData = {
    body?: {
        /**
         * Full-text search across subject, from, to, and body
         */
        text?: string;
        /**
         * Search in email subject
         */
        subject?: string;
        /**
         * Search in sender address or name
         */
        from?: string;
        /**
         * Search in recipient addresses
         */
        to?: string;
        /**
         * Search in email body content
         */
        body?: string;
        /**
         * Return messages since this date (Unix timestamp in milliseconds)
         */
        since?: number;
        /**
         * Return messages before this date (Unix timestamp in milliseconds)
         */
        before?: number;
        /**
         * Filter emails by attachment presence
         */
        hasAttachment?: boolean;
        /**
         * Filter by read/unread status (true = read, false = unread)
         */
        seen?: boolean;
        /**
         * Filter by flagged/starred status
         */
        flagged?: boolean;
        /**
         * Filter by replied-to status
         */
        answered?: boolean;
        /**
         * Filter by draft status
         */
        draft?: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: {
        /**
         * Sort order by email date
         */
        order?: 'newest' | 'oldest';
        /**
         * Maximum number of results to return
         */
        limit?: number;
        /**
         * Number of results to skip for pagination
         */
        offset?: number;
        /**
         * Comma-separated list of mailbox paths to search (searches all if not specified)
         */
        mailboxes?: string;
        /**
         * Comma-separated list of mailbox paths to exclude from search
         */
        excludeMailboxes?: string;
        /**
         * Include Trash/Deleted items folder in search
         */
        includeTrash?: boolean;
        /**
         * Include Spam/Junk folder in search
         */
        includeSpam?: boolean;
        /**
         * Include Drafts folder in search
         */
        includeDrafts?: boolean;
    };
    url: '/mail-accounts/{mailAccountID}/search';
};

export type PostMailAccountsByMailAccountIdSearchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsByMailAccountIdSearchError = PostMailAccountsByMailAccountIdSearchErrors[keyof PostMailAccountsByMailAccountIdSearchErrors];

export type PostMailAccountsByMailAccountIdSearchResponses = {
    /**
     * Search completed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Search completed successfully';
        data: {
            /**
             * Total number of matching emails across all searched mailboxes
             */
            total: number;
            /**
             * Number of mailboxes that were searched
             */
            mailboxesSearched: number;
            /**
             * Array of search results with mailbox information
             */
            results: Array<{
                /**
                 * Path of the mailbox containing this email
                 */
                mailboxPath: string;
                /**
                 * Display name of the mailbox
                 */
                mailboxName: string;
                /**
                 * Special use flag (e.g., \Sent, \Drafts, \Trash)
                 */
                specialUse?: string;
                mail: {
                    uid: number;
                    rawHeaders: {
                        [key: string]: string;
                    };
                    rawFlags: Array<string>;
                    from?: {
                        name?: string;
                        address: string;
                    };
                    to: Array<{
                        name?: string;
                        address: string;
                    }>;
                    cc: Array<{
                        name?: string;
                        address: string;
                    }>;
                    bcc: Array<{
                        name?: string;
                        address: string;
                    }>;
                    subject?: string;
                    references?: string | Array<string>;
                    date?: number;
                    flags?: {
                        seen?: boolean;
                        answered?: boolean;
                        flagged?: boolean;
                        deleted?: boolean;
                        draft?: boolean;
                        recent?: boolean;
                    };
                    replyTo?: Array<{
                        name?: string;
                        address: string;
                    }>;
                    messageId?: string;
                    inReplyTo?: string;
                    priority?: 'normal' | 'low' | 'high';
                    attachments: Array<{
                        filename?: string;
                        contentType: string;
                        size: number;
                        contentId?: string;
                        contentDisposition?: string;
                    }>;
                    body: {
                        text?: string;
                        html?: string;
                    };
                };
            }>;
        };
    };
};

export type PostMailAccountsByMailAccountIdSearchResponse = PostMailAccountsByMailAccountIdSearchResponses[keyof PostMailAccountsByMailAccountIdSearchResponses];

export type PostMailAccountsByMailAccountIdSearchCountData = {
    body?: {
        /**
         * Full-text search across subject, from, to, and body
         */
        text?: string;
        /**
         * Search in email subject
         */
        subject?: string;
        /**
         * Search in sender address or name
         */
        from?: string;
        /**
         * Search in recipient addresses
         */
        to?: string;
        /**
         * Search in email body content
         */
        body?: string;
        /**
         * Return messages since this date (Unix timestamp in milliseconds)
         */
        since?: number;
        /**
         * Return messages before this date (Unix timestamp in milliseconds)
         */
        before?: number;
        /**
         * Filter emails by attachment presence
         */
        hasAttachment?: boolean;
        /**
         * Filter by read/unread status (true = read, false = unread)
         */
        seen?: boolean;
        /**
         * Filter by flagged/starred status
         */
        flagged?: boolean;
        /**
         * Filter by replied-to status
         */
        answered?: boolean;
        /**
         * Filter by draft status
         */
        draft?: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: {
        /**
         * Sort order by email date
         */
        order?: 'newest' | 'oldest';
        /**
         * Comma-separated list of mailbox paths to search (searches all if not specified)
         */
        mailboxes?: string;
        /**
         * Comma-separated list of mailbox paths to exclude from search
         */
        excludeMailboxes?: string;
        /**
         * Include Trash/Deleted items folder in search
         */
        includeTrash?: boolean;
        /**
         * Include Spam/Junk folder in search
         */
        includeSpam?: boolean;
        /**
         * Include Drafts folder in search
         */
        includeDrafts?: boolean;
    };
    url: '/mail-accounts/{mailAccountID}/search/count';
};

export type PostMailAccountsByMailAccountIdSearchCountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsByMailAccountIdSearchCountError = PostMailAccountsByMailAccountIdSearchCountErrors[keyof PostMailAccountsByMailAccountIdSearchCountErrors];

export type PostMailAccountsByMailAccountIdSearchCountResponses = {
    /**
     * Count completed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Count completed successfully';
        data: {
            /**
             * Total number of matching emails across all searched mailboxes
             */
            total: number;
            /**
             * Number of mailboxes that were searched
             */
            mailboxesSearched: number;
            /**
             * Per-mailbox breakdown of matching emails, sorted by count descending
             */
            breakdown: Array<{
                /**
                 * Path of the mailbox
                 */
                mailboxPath: string;
                /**
                 * Display name of the mailbox
                 */
                mailboxName: string;
                /**
                 * Number of matching emails in this mailbox
                 */
                count: number;
            }>;
        };
    };
};

export type PostMailAccountsByMailAccountIdSearchCountResponse = PostMailAccountsByMailAccountIdSearchCountResponses[keyof PostMailAccountsByMailAccountIdSearchCountResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body?: {
        /**
         * Username for the account
         */
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Cannot delete user while packages are assigned
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while packages are assigned';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersByUserIdError = DeleteAdminUsersByUserIdErrors[keyof DeleteAdminUsersByUserIdErrors];

export type DeleteAdminUsersByUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponses[keyof DeleteAdminUsersByUserIdResponses];

export type GetAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersByUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersByUserIdError = GetAdminUsersByUserIdErrors[keyof GetAdminUsersByUserIdErrors];

export type GetAdminUsersByUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponses[keyof GetAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersByUserIdError = PutAdminUsersByUserIdErrors[keyof PutAdminUsersByUserIdErrors];

export type PutAdminUsersByUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponses[keyof PutAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdPasswordData = {
    body?: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersByUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersByUserIdPasswordError = PutAdminUsersByUserIdPasswordErrors[keyof PutAdminUsersByUserIdPasswordErrors];

export type PutAdminUsersByUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponses[keyof PutAdminUsersByUserIdPasswordResponses];
