// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:14123' | 'https://api.delivr.is-on.net' | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body?: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Please delete all mail accounts associated with this account before deleting the account
     */
    400: {
        success: false;
        code: 400;
        message: 'Please delete all mail accounts associated with this account before deleting the account';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        /**
         * Username for the account
         */
        username?: string;
        display_name?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body?: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysApiKeyIdError = DeleteAccountApikeysApiKeyIdErrors[keyof DeleteAccountApikeysApiKeyIdErrors];

export type DeleteAccountApikeysApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysApiKeyIdResponse = DeleteAccountApikeysApiKeyIdResponses[keyof DeleteAccountApikeysApiKeyIdResponses];

export type GetMailAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mail-accounts';
};

export type GetMailAccountsResponses = {
    /**
     * Mail accounts retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail accounts retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            display_name: string;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_username: string;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_username: string;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            is_default: boolean;
        }>;
    };
};

export type GetMailAccountsResponse = GetMailAccountsResponses[keyof GetMailAccountsResponses];

export type PostMailAccountsData = {
    body?: {
        display_name: string;
        smtp_host: string | string | string;
        /**
         * Port
         */
        smtp_port: number;
        smtp_username: string;
        smtp_password: string;
        smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        imap_host: string | string | string;
        /**
         * Port
         */
        imap_port: number;
        imap_username: string;
        imap_password: string;
        imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        is_default?: boolean;
    };
    path?: never;
    query?: never;
    url: '/mail-accounts';
};

export type PostMailAccountsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsError = PostMailAccountsErrors[keyof PostMailAccountsErrors];

export type PostMailAccountsResponses = {
    /**
     * Mail account created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account created successfully';
        data: {
            id: number;
        };
    };
};

export type PostMailAccountsResponse = PostMailAccountsResponses[keyof PostMailAccountsResponses];

export type DeleteMailAccountsMailAccountIdData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}';
};

export type DeleteMailAccountsMailAccountIdErrors = {
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type DeleteMailAccountsMailAccountIdError = DeleteMailAccountsMailAccountIdErrors[keyof DeleteMailAccountsMailAccountIdErrors];

export type DeleteMailAccountsMailAccountIdResponses = {
    /**
     * Mail account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account deleted successfully';
        data: null;
    };
};

export type DeleteMailAccountsMailAccountIdResponse = DeleteMailAccountsMailAccountIdResponses[keyof DeleteMailAccountsMailAccountIdResponses];

export type GetMailAccountsMailAccountIdData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}';
};

export type GetMailAccountsMailAccountIdErrors = {
    /**
     * Mail Account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail Account with the specified ID not found';
    };
};

export type GetMailAccountsMailAccountIdError = GetMailAccountsMailAccountIdErrors[keyof GetMailAccountsMailAccountIdErrors];

export type GetMailAccountsMailAccountIdResponses = {
    /**
     * Mail account retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account retrieved successfully';
        data: {
            id: number;
            created_at: number;
            display_name: string;
            smtp_host: string | string | string;
            /**
             * Port
             */
            smtp_port: number;
            smtp_username: string;
            smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            imap_host: string | string | string;
            /**
             * Port
             */
            imap_port: number;
            imap_username: string;
            imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
            is_default: boolean;
        };
    };
};

export type GetMailAccountsMailAccountIdResponse = GetMailAccountsMailAccountIdResponses[keyof GetMailAccountsMailAccountIdResponses];

export type PutMailAccountsMailAccountIdData = {
    body?: {
        display_name?: string;
        is_default?: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}';
};

export type PutMailAccountsMailAccountIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type PutMailAccountsMailAccountIdError = PutMailAccountsMailAccountIdErrors[keyof PutMailAccountsMailAccountIdErrors];

export type PutMailAccountsMailAccountIdResponses = {
    /**
     * Mail account updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account updated successfully';
        data: null;
    };
};

export type PutMailAccountsMailAccountIdResponse = PutMailAccountsMailAccountIdResponses[keyof PutMailAccountsMailAccountIdResponses];

export type PutMailAccountsMailAccountIdCredentialsData = {
    body?: {
        smtp_host: string | string | string;
        /**
         * Port
         */
        smtp_port: number;
        smtp_username: string;
        smtp_password: string;
        smtp_encryption: 'SSL' | 'STARTTLS' | 'NONE';
        imap_host: string | string | string;
        /**
         * Port
         */
        imap_port: number;
        imap_username: string;
        imap_password: string;
        imap_encryption: 'SSL' | 'STARTTLS' | 'NONE';
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/credentials';
};

export type PutMailAccountsMailAccountIdCredentialsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail account with the specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail account with the specified ID not found';
    };
};

export type PutMailAccountsMailAccountIdCredentialsError = PutMailAccountsMailAccountIdCredentialsErrors[keyof PutMailAccountsMailAccountIdCredentialsErrors];

export type PutMailAccountsMailAccountIdCredentialsResponses = {
    /**
     * Mail account credentials updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail account credentials updated successfully';
        data: null;
    };
};

export type PutMailAccountsMailAccountIdCredentialsResponse = PutMailAccountsMailAccountIdCredentialsResponses[keyof PutMailAccountsMailAccountIdCredentialsResponses];

export type GetMailAccountsMailAccountIdMailsData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: {
        mailbox?: string;
        limit?: number;
    };
    url: '/mail-accounts/{mailAccountID}/mails';
};

export type GetMailAccountsMailAccountIdMailsResponses = {
    /**
     * Mails retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mails retrieved successfully';
        data: Array<{
            uid: number;
            rawHeaders: {
                [key: string]: string;
            };
            from?: {
                name?: string;
                address: string;
            };
            to?: Array<{
                name?: string;
                address: string;
            }>;
            cc?: Array<{
                name?: string;
                address: string;
            }>;
            bcc?: Array<{
                name?: string;
                address: string;
            }>;
            subject?: string;
            inReplyTo?: string;
            replyTo?: {
                name?: string;
                address: string;
            };
            references?: string | Array<string>;
            date?: number;
            attachments: Array<{
                filename?: string;
                contentType: string;
                size: number;
                contentId?: string;
                contentDisposition?: string;
            }>;
            body?: {
                text?: string;
                html?: string;
            };
        }>;
    };
};

export type GetMailAccountsMailAccountIdMailsResponse = GetMailAccountsMailAccountIdMailsResponses[keyof GetMailAccountsMailAccountIdMailsResponses];

export type GetMailAccountsMailAccountIdMailsMailUidData = {
    body?: never;
    path: {
        mailAccountID: number;
        mailUID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/mails/{mailUID}';
};

export type GetMailAccountsMailAccountIdMailsMailUidErrors = {
    /**
     * Mail with specified UID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail with specified UID not found';
    };
};

export type GetMailAccountsMailAccountIdMailsMailUidError = GetMailAccountsMailAccountIdMailsMailUidErrors[keyof GetMailAccountsMailAccountIdMailsMailUidErrors];

export type GetMailAccountsMailAccountIdMailsMailUidResponses = {
    /**
     * Mail retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail retrieved successfully';
        data: {
            uid: number;
            rawHeaders: {
                [key: string]: string;
            };
            from?: {
                name?: string;
                address: string;
            };
            to?: Array<{
                name?: string;
                address: string;
            }>;
            cc?: Array<{
                name?: string;
                address: string;
            }>;
            bcc?: Array<{
                name?: string;
                address: string;
            }>;
            subject?: string;
            inReplyTo?: string;
            replyTo?: {
                name?: string;
                address: string;
            };
            references?: string | Array<string>;
            date?: number;
            attachments: Array<{
                filename?: string;
                contentType: string;
                size: number;
                contentId?: string;
                contentDisposition?: string;
            }>;
            body?: {
                text?: string;
                html?: string;
            };
        };
    };
};

export type GetMailAccountsMailAccountIdMailsMailUidResponse = GetMailAccountsMailAccountIdMailsMailUidResponses[keyof GetMailAccountsMailAccountIdMailsMailUidResponses];

export type GetMailAccountsMailAccountIdIdentitiesData = {
    body?: never;
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities';
};

export type GetMailAccountsMailAccountIdIdentitiesResponses = {
    /**
     * Mail identities retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identities retrieved successfully';
        data: Array<{
            id: number;
            mail_account_id: number;
            created_at: number;
            display_name: string;
            email_address: string;
            is_default: boolean;
        }>;
    };
};

export type GetMailAccountsMailAccountIdIdentitiesResponse = GetMailAccountsMailAccountIdIdentitiesResponses[keyof GetMailAccountsMailAccountIdIdentitiesResponses];

export type PostMailAccountsMailAccountIdIdentitiesData = {
    body?: {
        display_name: string;
        email_address: string;
        is_default: boolean;
    };
    path: {
        mailAccountID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities';
};

export type PostMailAccountsMailAccountIdIdentitiesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostMailAccountsMailAccountIdIdentitiesError = PostMailAccountsMailAccountIdIdentitiesErrors[keyof PostMailAccountsMailAccountIdIdentitiesErrors];

export type PostMailAccountsMailAccountIdIdentitiesResponses = {
    /**
     * Mail identity created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity created successfully';
        data: {
            id: number;
        };
    };
};

export type PostMailAccountsMailAccountIdIdentitiesResponse = PostMailAccountsMailAccountIdIdentitiesResponses[keyof PostMailAccountsMailAccountIdIdentitiesResponses];

export type DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdData = {
    body?: never;
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdError = DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors[keyof DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors];

export type DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses = {
    /**
     * Mail identity deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity deleted successfully';
        data: null;
    };
};

export type DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses[keyof DeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses];

export type GetMailAccountsMailAccountIdIdentitiesMailIdentityIdData = {
    body?: never;
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type GetMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors = {
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type GetMailAccountsMailAccountIdIdentitiesMailIdentityIdError = GetMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors[keyof GetMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors];

export type GetMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses = {
    /**
     * Mail identity retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity retrieved successfully';
        data: {
            id: number;
            created_at: number;
            display_name: string;
            email_address: string;
            is_default: boolean;
        };
    };
};

export type GetMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = GetMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses[keyof GetMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses];

export type PutMailAccountsMailAccountIdIdentitiesMailIdentityIdData = {
    body?: {
        display_name?: string;
        email_address?: string;
        is_default?: boolean;
    };
    path: {
        mailAccountID: number;
        mailIdentityID: number;
    };
    query?: never;
    url: '/mail-accounts/{mailAccountID}/identities/{mailIdentityID}';
};

export type PutMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Mail identity with the specified ID does not exist
     */
    404: {
        success: false;
        code: 404;
        message: 'Mail identity with the specified ID does not exist';
    };
};

export type PutMailAccountsMailAccountIdIdentitiesMailIdentityIdError = PutMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors[keyof PutMailAccountsMailAccountIdIdentitiesMailIdentityIdErrors];

export type PutMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses = {
    /**
     * Mail identity updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Mail identity updated successfully';
        data: null;
    };
};

export type PutMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = PutMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses[keyof PutMailAccountsMailAccountIdIdentitiesMailIdentityIdResponses];
