// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:14123' | 'https://api.delivr.is-on.net' | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body?: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        /**
         * Username for the account
         */
        username?: string;
        display_name?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body?: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysApiKeyIdError = DeleteAccountApikeysApiKeyIdErrors[keyof DeleteAccountApikeysApiKeyIdErrors];

export type DeleteAccountApikeysApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysApiKeyIdResponse = DeleteAccountApikeysApiKeyIdResponses[keyof DeleteAccountApikeysApiKeyIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body?: {
        /**
         * Username for the account
         */
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersUserIdErrors = {
    /**
     * Cannot delete user while packages are assigned
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while packages are assigned';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersUserIdError = DeleteAdminUsersUserIdErrors[keyof DeleteAdminUsersUserIdErrors];

export type DeleteAdminUsersUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersUserIdResponse = DeleteAdminUsersUserIdResponses[keyof DeleteAdminUsersUserIdResponses];

export type GetAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersUserIdError = GetAdminUsersUserIdErrors[keyof GetAdminUsersUserIdErrors];

export type GetAdminUsersUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type GetAdminUsersUserIdResponse = GetAdminUsersUserIdResponses[keyof GetAdminUsersUserIdResponses];

export type PutAdminUsersUserIdData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersUserIdError = PutAdminUsersUserIdErrors[keyof PutAdminUsersUserIdErrors];

export type PutAdminUsersUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'user';
        };
    };
};

export type PutAdminUsersUserIdResponse = PutAdminUsersUserIdResponses[keyof PutAdminUsersUserIdResponses];

export type PutAdminUsersUserIdPasswordData = {
    body?: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersUserIdPasswordError = PutAdminUsersUserIdPasswordErrors[keyof PutAdminUsersUserIdPasswordErrors];

export type PutAdminUsersUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersUserIdPasswordResponse = PutAdminUsersUserIdPasswordResponses[keyof PutAdminUsersUserIdPasswordResponses];
