// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPostAuthLoginBody = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordBody = z.object({
    reset_token: z.string().min(1),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestBody = z.object({
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    })
});

export const zPutAccountBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/).optional(),
    display_name: z.string().optional(),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/).optional()
});

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordBody = z.object({
    current_password: z.string(),
    new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    }))
});

export const zPostAccountApikeysBody = z.object({
    description: z.string().min(1).max(255),
    expires_at: z.union([
        z.literal('7d'),
        z.literal('30d'),
        z.literal('90d'),
        z.literal('180d'),
        z.literal('365d')
    ]).nullable()
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetAccountApikeysByApiKeyIdPath = z.object({
    apiKeyID: z.string().min(1).max(255)
});

/**
 * API key retrieved successfully
 */
export const zGetAccountApikeysByApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key retrieved successfully'),
    data: z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable()
    })
});

/**
 * Remote content policy retrieved successfully
 */
export const zGetAccountPreferencesRemoteContentPolicyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Remote content policy retrieved successfully'),
    data: z.object({
        addresses: z.record(z.string(), z.enum(['allow', 'block'])).optional().default({}),
        domains: z.record(z.string(), z.enum(['allow', 'block'])).optional().default({})
    })
});

export const zPutAccountPreferencesRemoteContentPolicyBody = z.object({
    addresses: z.record(z.string(), z.enum(['allow', 'block'])).optional().default({}),
    domains: z.record(z.string(), z.enum(['allow', 'block'])).optional().default({})
});

/**
 * Remote content policy updated successfully
 */
export const zPutAccountPreferencesRemoteContentPolicyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Remote content policy updated successfully'),
    data: z.null()
});

/**
 * Mail list page size retrieved successfully
 */
export const zGetAccountPreferencesMailListPageSizeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail list page size retrieved successfully'),
    data: z.object({
        pageSize: z.union([
            z.literal(25),
            z.literal(50),
            z.literal(100),
            z.literal('all')
        ]).optional().default(25)
    })
});

export const zPutAccountPreferencesMailListPageSizeBody = z.object({
    pageSize: z.union([
        z.literal(25),
        z.literal(50),
        z.literal(100),
        z.literal('all')
    ]).optional().default(25)
});

/**
 * Mail list page size updated successfully
 */
export const zPutAccountPreferencesMailListPageSizeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail list page size updated successfully'),
    data: z.null()
});

export const zGetMailAccountsQuery = z.object({
    withMailboxes: z.boolean().optional().default(false)
});

/**
 * Mail accounts retrieved successfully
 */
export const zGetMailAccountsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail accounts retrieved successfully'),
    data: z.union([
        z.array(z.object({
            id: z.int().gt(0).lte(9007199254740991),
            created_at: z.int().gt(0).lte(9007199254740991),
            display_name: z.string().min(1).max(255),
            is_default: z.boolean(),
            smtp_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            smtp_port: z.int().gte(1).lte(65535),
            smtp_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            smtp_username: z.string().min(1).max(255),
            imap_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            imap_port: z.int().gte(1).lte(65535),
            imap_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            imap_username: z.string().min(1).max(255)
        })),
        z.array(z.object({
            id: z.int().gt(0).lte(9007199254740991),
            created_at: z.int().gt(0).lte(9007199254740991),
            display_name: z.string().min(1).max(255),
            is_default: z.boolean(),
            smtp_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            smtp_port: z.int().gte(1).lte(65535),
            smtp_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            smtp_username: z.string().min(1).max(255),
            imap_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            imap_port: z.int().gte(1).lte(65535),
            imap_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            imap_username: z.string().min(1).max(255),
            mailboxes: z.array(z.object({
                name: z.string(),
                path: z.string(),
                delimiter: z.string(),
                parent: z.array(z.string()),
                parentPath: z.string(),
                flags: z.array(z.string()),
                specialUse: z.string().optional(),
                status: z.object({
                    messages: z.number().gte(0),
                    recent: z.number().gte(0),
                    unseen: z.number().gte(0)
                })
            }))
        }))
    ])
});

export const zPostMailAccountsBody = z.object({
    display_name: z.string().min(1).max(255),
    is_default: z.boolean().optional(),
    smtp_host: z.union([
        z.union([
            z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
            z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
        ]),
        z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
    ]),
    smtp_port: z.int().gte(1).lte(65535),
    smtp_encryption: z.enum([
        'SSL',
        'STARTTLS',
        'NONE'
    ]),
    smtp_username: z.string().min(1).max(255),
    smtp_password: z.string().min(1).max(1023),
    imap_host: z.union([
        z.union([
            z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
            z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
        ]),
        z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
    ]),
    imap_port: z.int().gte(1).lte(65535),
    imap_encryption: z.enum([
        'SSL',
        'STARTTLS',
        'NONE'
    ]),
    imap_username: z.string().min(1).max(255),
    imap_password: z.string().min(1).max(1023)
});

/**
 * Mail account created successfully
 */
export const zPostMailAccountsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account created successfully'),
    data: z.object({
        id: z.number()
    })
});

export const zDeleteMailAccountsByMailAccountIdPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mail account deleted successfully
 */
export const zDeleteMailAccountsByMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdPath = z.object({
    mailAccountID: z.number().gt(0)
});

export const zGetMailAccountsByMailAccountIdQuery = z.object({
    withMailboxes: z.boolean().optional().default(false)
});

/**
 * Mail account retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account retrieved successfully'),
    data: z.union([
        z.object({
            id: z.int().gt(0).lte(9007199254740991),
            created_at: z.int().gt(0).lte(9007199254740991),
            display_name: z.string().min(1).max(255),
            is_default: z.boolean(),
            smtp_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            smtp_port: z.int().gte(1).lte(65535),
            smtp_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            smtp_username: z.string().min(1).max(255),
            imap_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            imap_port: z.int().gte(1).lte(65535),
            imap_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            imap_username: z.string().min(1).max(255)
        }),
        z.object({
            id: z.int().gt(0).lte(9007199254740991),
            created_at: z.int().gt(0).lte(9007199254740991),
            display_name: z.string().min(1).max(255),
            is_default: z.boolean(),
            smtp_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            smtp_port: z.int().gte(1).lte(65535),
            smtp_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            smtp_username: z.string().min(1).max(255),
            imap_host: z.union([
                z.union([
                    z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                    z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
                ]),
                z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
            ]),
            imap_port: z.int().gte(1).lte(65535),
            imap_encryption: z.enum([
                'SSL',
                'STARTTLS',
                'NONE'
            ]),
            imap_username: z.string().min(1).max(255),
            mailboxes: z.array(z.object({
                name: z.string(),
                path: z.string(),
                delimiter: z.string(),
                parent: z.array(z.string()),
                parentPath: z.string(),
                flags: z.array(z.string()),
                specialUse: z.string().optional(),
                status: z.object({
                    messages: z.number().gte(0),
                    recent: z.number().gte(0),
                    unseen: z.number().gte(0)
                })
            }))
        })
    ])
});

export const zPutMailAccountsByMailAccountIdBody = z.object({
    display_name: z.string().min(1).max(255).optional(),
    is_default: z.boolean().optional()
});

export const zPutMailAccountsByMailAccountIdPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mail account updated successfully
 */
export const zPutMailAccountsByMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account updated successfully'),
    data: z.null()
});

export const zPutMailAccountsByMailAccountIdCredentialsBody = z.object({
    smtp_host: z.union([
        z.union([
            z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
            z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
        ]),
        z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
    ]),
    smtp_port: z.int().gte(1).lte(65535),
    smtp_username: z.string().min(1).max(255),
    smtp_password: z.string().min(1).max(1023),
    smtp_encryption: z.enum([
        'SSL',
        'STARTTLS',
        'NONE'
    ]),
    imap_host: z.union([
        z.union([
            z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
            z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
        ]),
        z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
    ]),
    imap_port: z.int().gte(1).lte(65535),
    imap_username: z.string().min(1).max(255),
    imap_password: z.string().min(1).max(1023),
    imap_encryption: z.enum([
        'SSL',
        'STARTTLS',
        'NONE'
    ])
});

export const zPutMailAccountsByMailAccountIdCredentialsPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mail account credentials updated successfully
 */
export const zPutMailAccountsByMailAccountIdCredentialsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account credentials updated successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdMailboxesPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mailboxes retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdMailboxesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailboxes retrieved successfully'),
    data: z.array(z.object({
        name: z.string(),
        path: z.string(),
        delimiter: z.string(),
        parent: z.array(z.string()),
        parentPath: z.string(),
        flags: z.array(z.string()),
        specialUse: z.string().optional(),
        status: z.object({
            messages: z.number().gte(0),
            recent: z.number().gte(0),
            unseen: z.number().gte(0)
        })
    }))
});

export const zPostMailAccountsByMailAccountIdMailboxesBody = z.object({
    path: z.string()
});

export const zPostMailAccountsByMailAccountIdMailboxesPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mailbox created successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailbox created successfully'),
    data: z.null()
});

export const zDeleteMailAccountsByMailAccountIdMailboxesByMailboxPathPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mailbox deleted successfully
 */
export const zDeleteMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailbox deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mailbox info retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailbox info retrieved successfully'),
    data: z.object({
        name: z.string(),
        path: z.string(),
        delimiter: z.string(),
        parent: z.array(z.string()),
        parentPath: z.string(),
        flags: z.array(z.string()),
        specialUse: z.string().optional(),
        status: z.object({
            messages: z.number().gte(0),
            recent: z.number().gte(0),
            unseen: z.number().gte(0)
        })
    })
});

export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathBody = z.object({
    path: z.string()
});

export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mailbox updated successfully
 */
export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailbox updated successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mailbox status retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathStatusResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mailbox status retrieved successfully'),
    data: z.object({
        messages: z.number().gte(0),
        recent: z.number().gte(0),
        unseen: z.number().gte(0)
    })
});

export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(10),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    order: z.enum(['newest', 'oldest']).optional(),
    searchString: z.string().optional()
});

/**
 * Mails retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mails retrieved successfully'),
    data: z.array(z.object({
        uid: z.number().gte(0),
        rawHeaders: z.record(z.string(), z.string()),
        rawFlags: z.array(z.string()),
        from: z.object({
            name: z.string().optional(),
            address: z.string()
        }).optional(),
        to: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        cc: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        bcc: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        subject: z.string().optional(),
        references: z.union([
            z.string(),
            z.array(z.string())
        ]).optional(),
        date: z.number().optional(),
        flags: z.object({
            seen: z.boolean().optional(),
            answered: z.boolean().optional(),
            flagged: z.boolean().optional(),
            deleted: z.boolean().optional(),
            draft: z.boolean().optional(),
            recent: z.boolean().optional()
        }).optional(),
        replyTo: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })).optional(),
        messageId: z.string().optional(),
        inReplyTo: z.string().optional(),
        priority: z.enum([
            'normal',
            'low',
            'high'
        ]).optional(),
        attachments: z.array(z.object({
            filename: z.string().optional(),
            contentType: z.string(),
            size: z.number(),
            contentId: z.string().optional(),
            contentDisposition: z.string().optional()
        })),
        body: z.object({
            text: z.string().optional(),
            html: z.string().optional()
        })
    }))
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBody = z.object({
    from: z.object({
        name: z.string().optional(),
        address: z.string()
    }).optional(),
    to: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })),
    cc: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })),
    bcc: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })),
    subject: z.string().optional(),
    references: z.union([
        z.string(),
        z.array(z.string())
    ]).optional(),
    flags: z.object({
        seen: z.boolean().optional(),
        answered: z.boolean().optional(),
        flagged: z.boolean().optional(),
        deleted: z.boolean().optional(),
        draft: z.boolean().optional(),
        recent: z.boolean().optional()
    }).optional(),
    replyTo: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })).optional(),
    messageId: z.string().optional(),
    inReplyTo: z.string().optional(),
    priority: z.enum([
        'normal',
        'low',
        'high'
    ]).optional(),
    body: z.object({
        text: z.string().optional(),
        html: z.string().optional()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mail created successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail created successfully'),
    data: z.object({
        uid: z.number()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkMoveBody = z.object({
    uids: z.array(z.number()).min(1),
    targetMailbox: z.string()
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkMovePath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mails moved successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkMoveResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mails moved successfully'),
    data: z.object({
        success: z.boolean()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkCopyBody = z.object({
    uids: z.array(z.number()).min(1),
    targetMailbox: z.string()
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkCopyPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mails copied successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkCopyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mails copied successfully'),
    data: z.object({
        success: z.boolean()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkDeleteBody = z.object({
    uids: z.array(z.number()).min(1),
    permanent: z.boolean().optional().default(false)
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkDeletePath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string()
});

/**
 * Mails deleted successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsBulkDeleteResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mails deleted successfully'),
    data: z.object({
        success: z.boolean()
    })
});

export const zDeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string(),
    mailUID: z.number()
});

export const zDeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidQuery = z.object({
    permanent: z.boolean().optional().default(false)
});

/**
 * Mail deleted successfully
 */
export const zDeleteMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail deleted successfully'),
    data: z.object({
        success: z.boolean()
    })
});

export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string(),
    mailUID: z.number()
});

/**
 * Mail retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail retrieved successfully'),
    data: z.object({
        uid: z.number().gte(0),
        rawHeaders: z.record(z.string(), z.string()),
        rawFlags: z.array(z.string()),
        from: z.object({
            name: z.string().optional(),
            address: z.string()
        }).optional(),
        to: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        cc: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        bcc: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })),
        subject: z.string().optional(),
        references: z.union([
            z.string(),
            z.array(z.string())
        ]).optional(),
        date: z.number().optional(),
        flags: z.object({
            seen: z.boolean().optional(),
            answered: z.boolean().optional(),
            flagged: z.boolean().optional(),
            deleted: z.boolean().optional(),
            draft: z.boolean().optional(),
            recent: z.boolean().optional()
        }).optional(),
        replyTo: z.array(z.object({
            name: z.string().optional(),
            address: z.string()
        })).optional(),
        messageId: z.string().optional(),
        inReplyTo: z.string().optional(),
        priority: z.enum([
            'normal',
            'low',
            'high'
        ]).optional(),
        attachments: z.array(z.object({
            filename: z.string().optional(),
            contentType: z.string(),
            size: z.number(),
            contentId: z.string().optional(),
            contentDisposition: z.string().optional()
        })),
        body: z.object({
            text: z.string().optional(),
            html: z.string().optional()
        })
    })
});

export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidBody = z.object({
    from: z.object({
        name: z.string().optional(),
        address: z.string()
    }).optional(),
    to: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })).optional(),
    cc: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })).optional(),
    bcc: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })).optional(),
    subject: z.string().optional(),
    references: z.union([
        z.string(),
        z.array(z.string())
    ]).optional(),
    flags: z.object({
        seen: z.boolean().optional(),
        answered: z.boolean().optional(),
        flagged: z.boolean().optional(),
        deleted: z.boolean().optional(),
        draft: z.boolean().optional(),
        recent: z.boolean().optional()
    }).optional(),
    replyTo: z.array(z.object({
        name: z.string().optional(),
        address: z.string()
    })).optional(),
    messageId: z.string().optional(),
    inReplyTo: z.string().optional(),
    priority: z.enum([
        'normal',
        'low',
        'high'
    ]).optional(),
    body: z.object({
        text: z.string().optional(),
        html: z.string().optional()
    }).optional()
});

export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string(),
    mailUID: z.number()
});

/**
 * Mail updated successfully
 */
export const zPutMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail updated successfully'),
    data: z.object({
        success: z.boolean(),
        newUid: z.number().optional()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendBody = z.object({
    moveToSent: z.boolean().optional().default(true),
    deleteOriginal: z.boolean().optional().default(false)
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendPath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string(),
    mailUID: z.number()
});

/**
 * Mail sent successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidSendResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail sent successfully'),
    data: z.object({
        messageId: z.string().optional()
    })
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveBody = z.object({
    targetMailbox: z.string()
});

export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMovePath = z.object({
    mailAccountID: z.number().gt(0),
    mailboxPath: z.string(),
    mailUID: z.number()
});

/**
 * Mail moved successfully
 */
export const zPostMailAccountsByMailAccountIdMailboxesByMailboxPathMailsByMailUidMoveResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail moved successfully'),
    data: z.object({
        newUid: z.number().optional()
    })
});

export const zGetMailAccountsByMailAccountIdIdentitiesPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mail identities retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdIdentitiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identities retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gt(0).lte(9007199254740991),
        mail_account_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        display_name: z.string().min(1).max(255),
        email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        is_default: z.boolean()
    }))
});

export const zPostMailAccountsByMailAccountIdIdentitiesBody = z.object({
    display_name: z.string().min(1).max(255),
    email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    is_default: z.boolean()
});

export const zPostMailAccountsByMailAccountIdIdentitiesPath = z.object({
    mailAccountID: z.number().gt(0)
});

/**
 * Mail identity created successfully
 */
export const zPostMailAccountsByMailAccountIdIdentitiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity created successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991)
    })
});

export const zDeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdPath = z.object({
    mailAccountID: z.number().gt(0),
    mailIdentityID: z.number().gt(0)
});

/**
 * Mail identity deleted successfully
 */
export const zDeleteMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdPath = z.object({
    mailAccountID: z.number().gt(0),
    mailIdentityID: z.number().gt(0)
});

/**
 * Mail identity retrieved successfully
 */
export const zGetMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity retrieved successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        display_name: z.string().min(1).max(255),
        email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        is_default: z.boolean()
    })
});

export const zPutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdBody = z.object({
    display_name: z.string().min(1).max(255).optional(),
    email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/).optional(),
    is_default: z.boolean().optional()
});

export const zPutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdPath = z.object({
    mailAccountID: z.number().gt(0),
    mailIdentityID: z.number().gt(0)
});

/**
 * Mail identity updated successfully
 */
export const zPutMailAccountsByMailAccountIdIdentitiesByMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity updated successfully'),
    data: z.null()
});

export const zGetMailAccountsByMailAccountIdSearchPath = z.object({
    mailAccountID: z.number().gt(0)
});

export const zGetMailAccountsByMailAccountIdSearchQuery = z.object({
    q: z.string().min(1),
    order: z.enum(['newest', 'oldest']).optional(),
    limit: z.int().gte(1).lte(100).optional().default(25),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    includeTrash: z.boolean().optional().default(false),
    includeSpam: z.boolean().optional().default(false)
});

/**
 * Search completed successfully
 */
export const zGetMailAccountsByMailAccountIdSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search completed successfully'),
    data: z.object({
        total: z.int().gte(0).lte(9007199254740991),
        mailboxesSearched: z.int().gte(0).lte(9007199254740991),
        results: z.array(z.object({
            mailboxPath: z.string(),
            mailboxName: z.string(),
            specialUse: z.string().optional(),
            mail: z.object({
                uid: z.number().gte(0),
                rawHeaders: z.record(z.string(), z.string()),
                rawFlags: z.array(z.string()),
                from: z.object({
                    name: z.string().optional(),
                    address: z.string()
                }).optional(),
                to: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                cc: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                bcc: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                subject: z.string().optional(),
                references: z.union([
                    z.string(),
                    z.array(z.string())
                ]).optional(),
                date: z.number().optional(),
                flags: z.object({
                    seen: z.boolean().optional(),
                    answered: z.boolean().optional(),
                    flagged: z.boolean().optional(),
                    deleted: z.boolean().optional(),
                    draft: z.boolean().optional(),
                    recent: z.boolean().optional()
                }).optional(),
                replyTo: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })).optional(),
                messageId: z.string().optional(),
                inReplyTo: z.string().optional(),
                priority: z.enum([
                    'normal',
                    'low',
                    'high'
                ]).optional(),
                attachments: z.array(z.object({
                    filename: z.string().optional(),
                    contentType: z.string(),
                    size: z.number(),
                    contentId: z.string().optional(),
                    contentDisposition: z.string().optional()
                })),
                body: z.object({
                    text: z.string().optional(),
                    html: z.string().optional()
                })
            })
        }))
    })
});

export const zPostMailAccountsByMailAccountIdSearchBody = z.object({
    text: z.string().optional(),
    subject: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    body: z.string().optional(),
    since: z.int().gt(0).lte(9007199254740991).optional(),
    before: z.int().gt(0).lte(9007199254740991).optional(),
    hasAttachment: z.boolean().optional(),
    seen: z.boolean().optional(),
    flagged: z.boolean().optional(),
    answered: z.boolean().optional(),
    draft: z.boolean().optional()
});

export const zPostMailAccountsByMailAccountIdSearchPath = z.object({
    mailAccountID: z.number().gt(0)
});

export const zPostMailAccountsByMailAccountIdSearchQuery = z.object({
    order: z.enum(['newest', 'oldest']).optional(),
    limit: z.int().gte(1).lte(100).optional().default(50),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    mailboxes: z.string().optional(),
    excludeMailboxes: z.string().optional(),
    includeTrash: z.boolean().optional().default(false),
    includeSpam: z.boolean().optional().default(false),
    includeDrafts: z.boolean().optional().default(true)
});

/**
 * Search completed successfully
 */
export const zPostMailAccountsByMailAccountIdSearchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Search completed successfully'),
    data: z.object({
        total: z.int().gte(0).lte(9007199254740991),
        mailboxesSearched: z.int().gte(0).lte(9007199254740991),
        results: z.array(z.object({
            mailboxPath: z.string(),
            mailboxName: z.string(),
            specialUse: z.string().optional(),
            mail: z.object({
                uid: z.number().gte(0),
                rawHeaders: z.record(z.string(), z.string()),
                rawFlags: z.array(z.string()),
                from: z.object({
                    name: z.string().optional(),
                    address: z.string()
                }).optional(),
                to: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                cc: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                bcc: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })),
                subject: z.string().optional(),
                references: z.union([
                    z.string(),
                    z.array(z.string())
                ]).optional(),
                date: z.number().optional(),
                flags: z.object({
                    seen: z.boolean().optional(),
                    answered: z.boolean().optional(),
                    flagged: z.boolean().optional(),
                    deleted: z.boolean().optional(),
                    draft: z.boolean().optional(),
                    recent: z.boolean().optional()
                }).optional(),
                replyTo: z.array(z.object({
                    name: z.string().optional(),
                    address: z.string()
                })).optional(),
                messageId: z.string().optional(),
                inReplyTo: z.string().optional(),
                priority: z.enum([
                    'normal',
                    'low',
                    'high'
                ]).optional(),
                attachments: z.array(z.object({
                    filename: z.string().optional(),
                    contentType: z.string(),
                    size: z.number(),
                    contentId: z.string().optional(),
                    contentDisposition: z.string().optional()
                })),
                body: z.object({
                    text: z.string().optional(),
                    html: z.string().optional()
                })
            })
        }))
    })
});

export const zPostMailAccountsByMailAccountIdSearchCountBody = z.object({
    text: z.string().optional(),
    subject: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    body: z.string().optional(),
    since: z.int().gt(0).lte(9007199254740991).optional(),
    before: z.int().gt(0).lte(9007199254740991).optional(),
    hasAttachment: z.boolean().optional(),
    seen: z.boolean().optional(),
    flagged: z.boolean().optional(),
    answered: z.boolean().optional(),
    draft: z.boolean().optional()
});

export const zPostMailAccountsByMailAccountIdSearchCountPath = z.object({
    mailAccountID: z.number().gt(0)
});

export const zPostMailAccountsByMailAccountIdSearchCountQuery = z.object({
    order: z.enum(['newest', 'oldest']).optional(),
    mailboxes: z.string().optional(),
    excludeMailboxes: z.string().optional(),
    includeTrash: z.boolean().optional().default(false),
    includeSpam: z.boolean().optional().default(false),
    includeDrafts: z.boolean().optional().default(true)
});

/**
 * Count completed successfully
 */
export const zPostMailAccountsByMailAccountIdSearchCountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Count completed successfully'),
    data: z.object({
        total: z.int().gte(0).lte(9007199254740991),
        mailboxesSearched: z.int().gte(0).lte(9007199254740991),
        breakdown: z.array(z.object({
            mailboxPath: z.string(),
            mailboxName: z.string(),
            count: z.int().gte(0).lte(9007199254740991)
        }))
    })
});

export const zGetAdminUsersQuery = z.object({
    role: z.enum(['admin', 'user']).optional(),
    search: z.string().min(1).max(64).optional(),
    limit: z.int().gte(1).lte(100).optional(),
    offset: z.int().gte(0).lte(9007199254740991).optional()
});

/**
 * Users retrieved successfully
 */
export const zGetAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    }))
});

export const zPostAdminUsersBody = z.object({
    username: z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/),
    display_name: z.string().min(1).max(64),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    role: z.enum(['admin', 'user']).optional(),
    password: z.string().min(8).max(128)
});

/**
 * User created successfully
 */
export const zPostAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('User created successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    })
});

export const zDeleteAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User deleted successfully
 */
export const zDeleteAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User deleted successfully'),
    data: z.null()
});

export const zGetAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User retrieved successfully
 */
export const zGetAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    })
});

export const zPutAdminUsersByUserIdBody = z.object({
    username: z.string().optional(),
    display_name: z.string().optional(),
    email: z.string().optional(),
    role: z.enum(['admin', 'user']).optional()
});

export const zPutAdminUsersByUserIdPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * User updated successfully
 */
export const zPutAdminUsersByUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User updated successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    })
});

export const zPutAdminUsersByUserIdPasswordBody = z.object({
    password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
});

export const zPutAdminUsersByUserIdPasswordPath = z.object({
    userId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Password reset successfully
 */
export const zPutAdminUsersByUserIdPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset successfully'),
    data: z.null()
});
