// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPostAuthLoginData = z.object({
    body: z.optional(z.object({
        username: z.string(),
        password: z.string()
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

export const zGetAuthSessionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum(['admin', 'user']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPostAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordData = z.object({
    body: z.optional(z.object({
        reset_token: z.string().min(1),
        new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestData = z.object({
    body: z.optional(z.object({
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

export const zDeleteAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

export const zGetAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum(['admin', 'user'])
    })
});

export const zPutAccountData = z.object({
    body: z.optional(z.object({
        username: z.optional(z.string().min(5).max(40).regex(/^(?!.*[.-]{2})(?!.*--)(?!.*\.\.)[a-z0-9](?:[a-z0-9._-]{3,38}[a-z0-9_])?$/)),
        display_name: z.optional(z.string()),
        email: z.optional(z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordData = z.object({
    body: z.optional(z.object({
        current_password: z.string(),
        new_password: z.string().min(8).max(50).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

export const zGetAccountApikeysData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ])
    }))
});

export const zPostAccountApikeysData = z.object({
    body: z.optional(z.object({
        description: z.string(),
        expires_at: z.union([
            z.literal('7d'),
            z.literal('30d'),
            z.literal('90d'),
            z.literal('180d'),
            z.literal('365d'),
            z.null()
        ])
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysApiKeyIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        apiKeyID: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Mail accounts retrieved successfully
 */
export const zGetMailAccountsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail accounts retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gt(0).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        smtp_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        smtp_port: z.int().gte(1).lte(65535),
        smtp_username: z.string().min(1).max(255),
        smtp_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        imap_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        imap_port: z.int().gte(1).lte(65535),
        imap_username: z.string().min(1).max(255),
        imap_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        is_default: z.boolean()
    }))
});

export const zPostMailAccountsData = z.object({
    body: z.optional(z.object({
        smtp_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        smtp_port: z.int().gte(1).lte(65535),
        smtp_username: z.string().min(1).max(255),
        smtp_password: z.string().min(1).max(1023),
        smtp_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        imap_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        imap_port: z.int().gte(1).lte(65535),
        imap_username: z.string().min(1).max(255),
        imap_password: z.string().min(1).max(1023),
        imap_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        is_default: z.boolean()
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Mail account created successfully
 */
export const zPostMailAccountsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account created successfully'),
    data: z.object({
        id: z.number()
    })
});

export const zDeleteMailAccountsMailAccountIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail account deleted successfully
 */
export const zDeleteMailAccountsMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsMailAccountIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail account retrieved successfully
 */
export const zGetMailAccountsMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account retrieved successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        smtp_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        smtp_port: z.int().gte(1).lte(65535),
        smtp_username: z.string().min(1).max(255),
        smtp_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        imap_host: z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ]),
        imap_port: z.int().gte(1).lte(65535),
        imap_username: z.string().min(1).max(255),
        imap_encryption: z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ]),
        is_default: z.boolean()
    })
});

export const zPutMailAccountsMailAccountIdData = z.object({
    body: z.optional(z.object({
        smtp_host: z.optional(z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ])),
        smtp_port: z.optional(z.int().gte(1).lte(65535)),
        smtp_username: z.optional(z.string().min(1).max(255)),
        smtp_password: z.optional(z.string().min(1).max(1023)),
        smtp_encryption: z.optional(z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ])),
        imap_host: z.optional(z.union([
            z.union([
                z.ipv4().regex(/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/),
                z.ipv6().regex(/^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/)
            ]),
            z.string().regex(/^(?=.{1,253}\.?$)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[-0-9a-zA-Z]{0,61}[0-9a-zA-Z])?)*\.?$/)
        ])),
        imap_port: z.optional(z.int().gte(1).lte(65535)),
        imap_username: z.optional(z.string().min(1).max(255)),
        imap_password: z.optional(z.string().min(1).max(1023)),
        imap_encryption: z.optional(z.enum([
            'SSL',
            'STARTTLS',
            'NONE'
        ])),
        is_default: z.optional(z.boolean())
    })),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail account updated successfully
 */
export const zPutMailAccountsMailAccountIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail account updated successfully'),
    data: z.null()
});

export const zGetMailAccountsMailAccountIdMailsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mails retrieved successfully
 */
export const zGetMailAccountsMailAccountIdMailsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mails retrieved successfully'),
    data: z.array(z.record(z.string(), z.unknown()))
});

export const zGetMailAccountsMailAccountIdIdentitiesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail identities retrieved successfully
 */
export const zGetMailAccountsMailAccountIdIdentitiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identities retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gt(0).lte(9007199254740991),
        mail_account_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        display_name: z.string().min(1).max(255),
        email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        is_default: z.boolean()
    }))
});

export const zPostMailAccountsMailAccountIdIdentitiesData = z.object({
    body: z.optional(z.object({
        display_name: z.string().min(1).max(255),
        email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        is_default: z.boolean()
    })),
    path: z.object({
        mailAccountID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail identity created successfully
 */
export const zPostMailAccountsMailAccountIdIdentitiesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity created successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991)
    })
});

export const zDeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0),
        mailIdentityID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail identity deleted successfully
 */
export const zDeleteMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity deleted successfully'),
    data: z.null()
});

export const zGetMailAccountsMailAccountIdIdentitiesMailIdentityIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        mailAccountID: z.number().gt(0),
        mailIdentityID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail identity retrieved successfully
 */
export const zGetMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity retrieved successfully'),
    data: z.object({
        id: z.int().gt(0).lte(9007199254740991),
        created_at: z.int().gt(0).lte(9007199254740991),
        display_name: z.string().min(1).max(255),
        email_address: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        is_default: z.boolean()
    })
});

export const zPutMailAccountsMailAccountIdIdentitiesMailIdentityIdData = z.object({
    body: z.optional(z.object({
        display_name: z.optional(z.string().min(1).max(255)),
        email_address: z.optional(z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)),
        is_default: z.optional(z.boolean())
    })),
    path: z.object({
        mailAccountID: z.number().gt(0),
        mailIdentityID: z.number().gt(0)
    }),
    query: z.optional(z.never())
});

/**
 * Mail identity updated successfully
 */
export const zPutMailAccountsMailAccountIdIdentitiesMailIdentityIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Mail identity updated successfully'),
    data: z.null()
});
